icons_format = "{icon}"

[theme]
theme = "space-villain"

[icons]
icons = "awesome6"

#[[block]]
#block = "music"

[[block]]
block = "custom"
interval = 60
command = "khal list now 1d --format '{start-time' --day-format '' --notstarted | head -n1"

[[block]]
block = "maildir"
interval = 2
inboxes = [ "~/var/mail/*/*" ]
threshold_warning = 1
threshold_critical = 10
display_type = "new"

[[block]]
block = "battery"
device = "BAT0"
interval = 30
full_format = " $icon $percentage "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%d.%m %R') "

