# history settings
HISTFILE=$HOME/.zhistory

setopt APPEND_HISTORY

HISTSIZE=50000
SAVEHIST=30000

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY_TIME
setopt EXTENDED_HISTORY
