#! /bin/sh

 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# general                                                                     #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc config border_width            5
bspc config window_gap              20
bspc config split_ratio             0.5
bspc monitor -d I II III IV V

bspc config top_padding 						$TOP_PADDING

 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# colors                                                                      #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc config normal_border_color             "#080808"
bspc config focused_border_color            "#ACACAC"
bspc config active_border_color             "#ACACAC"

bspc config presel_border_color             "#585858"
bspc config presel_feedback_color           "#585858"

bspc config urgent_border_color             "#ACACAC"

 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# rules                                                                       #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

bspc rule -a "Eclipse" desktop="^1"

bspc rule -a "libreoffice-writer" desktop="^2"
bspc rule -a "MuPDF" desktop="^2" state=tiled

bspc rule -a "Gimp" desktop="^3" state=floating
bspc rule -a "Jameica 2.6.4" desktop="^3"
bspc rule -a "mpv" desktop="^3"

bspc rule -a "Signal Private Messenger" desktop="^4"

bspc rule -a "Firefox" desktop="^5"
