#!/usr/bin/env bash

. ${HOME}/.config/lemonbar/main_config

BATTERY_DIR="/sys/class/power_supply/BAT0"
URGENT_CAP=15

# print ac symbol
if [[ ! -d ${BATTERY_DIR} ]]; then
    echo "%{F${color4}}\uf244%{F-}"
fi

CAP=$(acpi -b | grep -e "[0-9]*%" -o | sed 's/%//')

LEVEL=$(( (${CAP} - 1) / 20 ))
ICON="f$(( 244 - ${LEVEL} ))"

if [[ -n $(cat ${BATTERY_DIR}/status | grep "Charging\|Unknown\|Full") ]]; then
    echo "\uf1e6 ${CAP}"
elif [[ ${URGENT_CAP} -ge ${CAP} ]]; then
    echo "%{F${color15}}\u${ICON} ${CAP}%{F-}"
else
    echo "\u${ICON} ${CAP}"
fi

