#!/bin/bash

. ${HOME}/.config/lemonbar/main_config

UPDATES=$(checkupdates-aur)

[[ -z "${UPDATES}" ]] && exit 0

INFO="\n----------\n${UPDATES}"

LINES=$(echo ${INFO} | wc -l)
LINES=$((LINES + 1))

(
echo "UPDATES $(echo ${UPDATES} | wc -l)";
echo ${INFOS} ) | dzen2 -x 625 -y 35 -w 185 -h 17 -l ${LINES} -sa c -fn "Misc Ohsnap:size=9" -p -e 'onstart=uncollapse;button1=exit;' -tw 6
