#!/bin/bash

. ${HOME}/.config/lemonbar/main_config

TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`
LINES=$(cal | wc -l)
LINES=$((LINES + 2))

(
date +'^bg($color0) '
date +''
# current month, highlight header and today
cal -m | sed -r -e "1,2 s/.*/^fg(${color2})&^fg()/"  -e "s/(^| )($TODAY)($| )/\1^bg(${color4})^fg(${color0})\2^fg()^bg()\3/") | dzen2 -x 890 -y 18 -w 185 -h 17 -l $LINES -sa c -fn 'Misc Ohsnap:size=9' -p -e 'onstart=uncollapse,hide;button1=exit;' -tw 6
