#!/usr/bin/env bash

. ${HOME}/.config/lemonbar/main_config
. ${HOME}/.cache/wal/colors.sh

if [[ $(mpc | egrep 'playing') ]]; then
  echo "%{F${color4}}\uf001 $(mpc | head -n1)%{F-}"
elif [[ -n $(mpc | grep "paused") ]]; then
  echo "%{F${color1}}\uf001 $(mpc | head -n1)%{F-}"
else
  echo "%{F${color1}}\uf001 OFF%{F-}"
fi
