#!/usr/bin/env bash

. ${HOME}/.config/lemonbar/main_config

SSID=$(iwgetid -r)
MAX_SIZE=10

[ -z "${SSID}" ] && echo "%{F${color1}}\uf1eb%{F-}" && exit 0

if [[ $(echo ${SSID} | wc -c) -gt ${MAX_SIZE} ]]; then
    echo "\uf1eb ${SSID:0:${MAX_SIZE}}.."
else
    echo "\uf1eb ${SSID}"
fi
