source_directories:
    - /Users/pkuehn/Documents
    - /Users/pkuehn/var
    - /Users/pkuehn/Pictures
    - /Users/pkuehn/src

repositories:
    - path: ssh://u487410@u487410.your-storagebox.de:23/./borg/peasec
      label: storagebox
    - path: ssh://u489939@u489939.your-storagebox.de:23/./borg/peasec
      label: storagebox-helsinki

archive_name_format: "macbook-{now:%Y-%m-%dT%H:%M:%S.%f}"

keep_hourly: 12
keep_daily: 15
keep_weekly: 8
keep_monthly: 6
keep_yearly: 4

exclude_patterns:
    - '*.pyc'
    - '**/.cache'
    - '**/.venv'
    - '**/.devenv'
    - 'src/**/target'

match_archives: '*'

exclude_caches: true

exclude_if_present:
    - .nobackup

lock_wait: 1

checks:
    - name: repository
    - name: archives
      frequency: 1 weeks

encryption_passcommand: 'cat /Users/pkuehn/Documents/misc/borg'
ssh_command: 'ssh -i /Users/pkuehn/.ssh/storagebox'
relocated_repo_access_is_ok: true
