source_directories:
    - /Users/pkuehn/Documents
    - /Users/pkuehn/var
    - /Users/pkuehn/Pictures
    - /Users/pkuehn/src

repositories:
    - path: ssh://u340000@u340000.your-storagebox.de:23/./borg/peasec
      label: storagebox

keep_hourly: 12
keep_daily: 15
keep_weekly: 8
keep_monthly: 6
keep_yearly: 4

exclude_patterns:
    - '*.pyc'
    - '**/.cache'
    - '**/.venv'
    - '**/.devenv'
    - '**/*CR2'
    - '**/*CR3'

match_archives: '*'

exclude_caches: true

exclude_if_present:
    - .nobackup

checks:
    - name: repository
    - name: archives
      frequency: 1 weeks

encryption_passcommand: 'cat /Users/pkuehn/Documents/misc/borg'
ssh_command: 'ssh -i /Users/pkuehn/.ssh/storagebox'
relocated_repo_access_is_ok: true
