music_directory         "~/Music"
playlist_directory      "~/Music/playlists"

db_file                 "~/.mpd/database"
log_file                "~/.mpd/log"
pid_file                "~/.mpd/pid"
state_file              "~/.mpd/state"
sticker_file            "~/.mpd/sticker.sql"

bind_to_address         "127.0.0.1"
port                    "6600"
filesystem_charset      "UTF-8"
# gapless_mp3_playback    "yes"

audio_output {
    type "osx"
    name "CoreAudio"
    mixer_type "software"
}

audio_output {
    type                "fifo"
    name                "my_fifo"
    path                "/tmp/mpd.fifo"
    format              "44100:16:2"
}
