#!/usr/bin/env zsh


. ${HOME}/.config/lemonbar/main_config

if [ $(pgrep -cx main_panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

# trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $GEOMETRY_HEIGHT

################################################################################
# clock                                                                        #
################################################################################

# while true; do
#     echo "C$(${SCRIPT_DIR}/clock)"
#     sleep 5
# done > "$PANEL_FIFO" &

################################################################################
# date                                                                         #
################################################################################

while true; do 
    echo "D$(${SCRIPT_DIR}/date)"
    sleep 5
done > $PANEL_FIFO &

################################################################################
# battery                                                                      #
################################################################################

while true; do
    echo "B$(${SCRIPT_DIR}/battery)"
    sleep 10;
done > "$PANEL_FIFO" &

################################################################################
# volume                                                                       #
################################################################################

while true; do
    echo "V$(${SCRIPT_DIR}/volume)"
    sleep 0.2
done > $PANEL_FIFO &

################################################################################
# wifi                                                                         #
################################################################################

while true; do
    echo "W$(${SCRIPT_DIR}/wifi)"
    sleep 3
done > $PANEL_FIFO &

################################################################################

cat "$PANEL_FIFO" | ${HOME}/.config/lemonbar/main_panel_bar | lemonbar -g ${GEOMETRY_WIDTH}x${GEOMETRY_HEIGHT}${GEOMETRY_X}${GEOMETRY_Y} -f "$PANEL_FONT" -f "$ICON_FONT" -F "$color4" -B "$color0" -u 2 -p -a 50 | zsh &

wait
