#!/bin/sh
#
# Example panel for LemonBoy's bar

. ${HOME}/.config/lemonbar/main_config

PADDING="  "

while read -r line ; do
    case $line in
        U*)
            # updates
            updates="%{A:${SCRIPT_DIR}/dzen_updates:}$PADDING${line#?}%{A}"
            ;;
        T*)
            # cpu temperature
            temp="$PADDING${line#?}"
            ;;
        D*)
            # date output
            date="%{A:${SCRIPT_DIR}/dzen_cal:}$PADDING${line#?}%{A}"
            ;;
        # C*)
        #     # clock output
        #     clock="$PADDING${line#?}$PADDING"
        #     ;;
        B*)
            # battery output
            battery="$PADDING${line#?}"
            ;;
        V*)
            # volume
            volume="$PADDING${line#?}"
            ;;
        # N*)
        #     # urgent desktop notification
        #     wifi="%{A:$(bspc wm -g > /tmp/panel-ws-fifo):}$PADDING${line#?}%{A}"
        #     ;;
        W*)
            # wifi
            wifi="%{A:${SCRIPT_DIR}/dzen_wifi:}$PADDING${line#?}%{A}"
            ;;
    esac
    printf "%s\n" "%{c}${wifi}${volume}${battery}${date}${clock}"
done

